-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "RoleKey" ADD VALUE 'SYS_SYSADMIN';
ALTER TYPE "RoleKey" ADD VALUE 'SYS_SUPPORT';
ALTER TYPE "RoleKey" ADD VALUE 'SYS_CREATOR';
ALTER TYPE "RoleKey" ADD VALUE 'SYS_ACCOUNTADMIN';
ALTER TYPE "RoleKey" ADD VALUE 'SYS_USER';
ALTER TYPE "RoleKey" ADD VALUE 'SYS_ADMINISTRATOR';
ALTER TYPE "RoleKey" ADD VALUE 'SYS_NONE';
ALTER TYPE "RoleKey" ADD VALUE 'INST_STUDENT';
ALTER TYPE "RoleKey" ADD VALUE 'INST_FACULTY';
ALTER TYPE "RoleKey" ADD VALUE 'INST_MEMBER';
ALTER TYPE "RoleKey" ADD VALUE 'INST_LEARNER';
ALTER TYPE "RoleKey" ADD VALUE 'INST_INSTRUCTOR';
ALTER TYPE "RoleKey" ADD VALUE 'INST_MENTOR';
ALTER TYPE "RoleKey" ADD VALUE 'INST_STAFF';
ALTER TYPE "RoleKey" ADD VALUE 'INST_ALUMNI';
ALTER TYPE "RoleKey" ADD VALUE 'INST_PROSPECTIVESTUDENT';
ALTER TYPE "RoleKey" ADD VALUE 'INST_GUEST';
ALTER TYPE "RoleKey" ADD VALUE 'INST_OTHER';
ALTER TYPE "RoleKey" ADD VALUE 'INST_ADMINISTRATOR';
ALTER TYPE "RoleKey" ADD VALUE 'INST_OBSERVER';
ALTER TYPE "RoleKey" ADD VALUE 'INST_NONE';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_LEARNER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_LEARNER_LEARNER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_LEARNER_NONCREDITLEARNER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_LEARNER_GUESTLEARNER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_LEARNER_EXTERNALLECTURER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_LEARNER_INSTRUCTOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_INSTRUCTOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_INSTRUCTOR_PRIMARYINSTRUCTOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_INSTRUCTOR_LECTURER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_INSTRUCTOR_GUESTINSTRUCTOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_INSTRUCTOR_EXTERNALINSTRUCTOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_CONTENT_DEVELOPER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_CONTENT_DEVELOPER_CONTENT_DEVELOPER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_CONTENT_DEVELOPER_LIBRARIAN';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_CONTENT_DEVELOPER_CONTENTEXPERT';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_CONTENT_DEVELOPER_EXTERNALCONTENTEXPERT';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MEMBER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MEMBER_MEMBER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MANAGER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MANAGER_AREAMANAGER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MANAGER_COURSECOORDINATOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MANAGER_OBSERVER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MANAGER_EXTERNALOBSERVER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_MENTOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_REVIEWER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_ADVISOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_AUDITOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_TUTOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_LEARNINGFACILITATOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_EXTERNALMENTOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_EXTERNALREVIEWER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_EXTERNALADVISOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_EXTERNALAUDITOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_EXTERNALTUTUR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_MENTOR_EXTERNALLEARNINGFACILITATOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_ADMINISTRATOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_ADMINISTRATOR_ADMINISTRATOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_ADMINISTRATOR_SUPPORT';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_ADMINISTRATOR_DEVELOPER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_ADMINISTRATOR_SYSTEMADMINISTRATOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_ADMINISTRATOR_EXTERNALSYSTEMADMINISTRATOR';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_ADMINISTRATOR_EXTERNALDEVELOPER';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_ADMINISTRATOR_EXTERNALSUPPORT';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_TEACHINGASSISTANT';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANT';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTSECTION';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTSECTIONASSOCIATION';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTOFFERING';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTTEMPLATE';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTGROUP';
ALTER TYPE "RoleKey" ADD VALUE 'CONTEXT_TEACHINGASSISTANT_GRADER';
